/**
 * Helpers that build the three text artifacts a Lightsail deploy ships
 * onto the VM via cloud-init Pulumi config secrets:
 *
 *  1. docker-compose.yml — the user's, fetched fresh from their repo at
 *     deploy time so the deployed compose always matches the branch.
 *  2. docker-compose.caddy.yml — platform-generated; runs Caddy as a
 *     sidecar container that joins the user's compose network.
 *  3. Caddyfile — platform-generated from heizenConfig.routing.
 *  4. .env — concatenated KEY=value lines from the Secrets tab.
 *
 * Everything returned here is plain text; the worker base64-encodes it
 * before passing to Pulumi.
 */

import type { HeizenConfig, ParsedCompose, RoutingEntry } from "@heizen/shared";

export interface LightsailArtifacts {
  composeYaml: string;
  caddyComposeYaml: string;
  caddyfile: string;
  envFile: string;
  ecrRegistry: string;
}

export interface BuildArtifactsInput {
  cfg: HeizenConfig;
  /** Raw docker-compose.yml from the user's repo. Source of truth. */
  composeYaml: string;
  /** Parsed view of the compose — used to validate routing entries
   *  point at services that actually exist. */
  parsedCompose: ParsedCompose;
  /** Concatenated KEY=value env vars from the Secrets tab (shared +
   *  per-service). Lightsail doesn't split per-service since the env
   *  applies to the whole compose project. */
  envVars: Record<string, string>;
  caddyEmail: string;
}

const ROUTING_ERR_PREFIX = "Lightsail routing config:";

export function validateRouting(
  routing: Record<string, RoutingEntry> | undefined,
  parsed: ParsedCompose,
): void {
  if (!routing || Object.keys(routing).length === 0) {
    throw new Error(
      `${ROUTING_ERR_PREFIX} no services exposed. Add at least one routing entry in the deploy form before deploying.`,
    );
  }

  const composeNames = new Set(parsed.services.map((s) => s.name));
  const seenDomains = new Set<string>();

  for (const [serviceName, entry] of Object.entries(routing)) {
    if (!composeNames.has(serviceName)) {
      throw new Error(
        `${ROUTING_ERR_PREFIX} service "${serviceName}" not found in docker-compose.yml. Re-index the repo if the compose changed.`,
      );
    }
    if (!entry.domain || !entry.domain.trim()) {
      throw new Error(
        `${ROUTING_ERR_PREFIX} service "${serviceName}" has no domain. Set one before deploying.`,
      );
    }
    const dom = entry.domain.trim().toLowerCase();
    if (seenDomains.has(dom)) {
      throw new Error(
        `${ROUTING_ERR_PREFIX} domain "${dom}" is assigned to multiple services. Each domain can only point at one service.`,
      );
    }
    seenDomains.add(dom);

    const svc = parsed.services.find((s) => s.name === serviceName)!;
    if (svc.hasBuild && !svc.image) {
      throw new Error(
        `${ROUTING_ERR_PREFIX} service "${serviceName}" uses build: but no image:. Lightsail can't build images on the box — push a prebuilt image to a registry and reference it via image:.`,
      );
    }
    const knownPorts = svc.ports.map((p) => p.container);
    if (knownPorts.length > 0 && !knownPorts.includes(entry.containerPort)) {
      throw new Error(
        `${ROUTING_ERR_PREFIX} service "${serviceName}" routes to port ${entry.containerPort}, but compose only exposes ${knownPorts.join(", ")}.`,
      );
    }
  }
}

export function buildCaddyfile(
  routing: Record<string, RoutingEntry>,
  caddyEmail: string,
): string {
  const lines: string[] = [];
  lines.push("# Generated by Heizen. Do not edit by hand.");
  lines.push("{");
  lines.push(`  email ${caddyEmail}`);
  lines.push("}");
  lines.push("");

  for (const [serviceName, entry] of Object.entries(routing)) {
    lines.push(`${entry.domain.trim()} {`);
    // SSE/WS friendly + sane timeouts. Matches what we use in prod for
    // the api service to keep deploy log streams alive.
    lines.push(`  reverse_proxy ${serviceName}:${entry.containerPort} {`);
    lines.push(`    flush_interval -1`);
    lines.push(`    transport http {`);
    lines.push(`      read_timeout 30m`);
    lines.push(`      write_timeout 30m`);
    lines.push(`    }`);
    lines.push(`  }`);
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Sidecar compose file that adds Caddy to the user's docker-compose
 * project. Merged at runtime via `docker compose -f user.yml -f caddy.yml`.
 *
 * Caddy joins the default network of the merged project (auto-named),
 * so it can reach user services by their compose service name —
 * "web", "api", etc. — without host port mapping. Only Caddy itself
 * publishes 80/443 to the host.
 */
export function buildCaddyComposeYaml(): string {
  return `# Generated by Heizen. Do not edit by hand.
services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - heizen_caddy_data:/data
      - heizen_caddy_config:/config

volumes:
  heizen_caddy_data:
  heizen_caddy_config:
`;
}

/**
 * Build the .env file content from a map. Keys are sorted for
 * deterministic output (helps with Pulumi state diffs).
 *
 * Values containing newlines (e.g. a PEM private key) are emitted in
 * quoted form. We don't escape interior double-quotes — the user is
 * responsible for not putting bare " in secret values, and most real
 * secrets are b64 / hex / base64 anyway.
 */
export function buildEnvFile(envVars: Record<string, string>): string {
  const lines: string[] = [];
  for (const key of Object.keys(envVars).sort()) {
    const value = envVars[key] ?? "";
    if (value.includes("\n")) {
      lines.push(`${key}="${value}"`);
    } else {
      lines.push(`${key}=${value}`);
    }
  }
  return lines.join("\n") + "\n";
}

export function buildLightsailArtifacts(
  input: BuildArtifactsInput,
): LightsailArtifacts {
  validateRouting(input.cfg.routing, input.parsedCompose);

  return {
    composeYaml: input.composeYaml,
    caddyComposeYaml: buildCaddyComposeYaml(),
    caddyfile: buildCaddyfile(input.cfg.routing!, input.caddyEmail),
    envFile: buildEnvFile(input.envVars),
    // ECR registry is derived from the image URI at the worker layer
    // (where we have STS creds + the ecr namespace). Filled by the
    // worker; this is just plumbing for clarity.
    ecrRegistry: "",
  };
}
