sonar.projectKey=opengig_workforce_6c110af7-0096-43bd-8096-63bf071b77de
sonar.projectName=Workforce

sonar.sources=apps,packages
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/*.spec.ts,**/*.spec.tsx,**/prisma/migrations/**
