import type { BadgeVariants } from "@repo/ui/components/badge";
import type {
	ApprovalStatusFilter,
	DisputeLogEntry,
	DisputeStatCard,
	HolidayEntry,
	HolidayStats,
	LocationTimekeeping,
	MissingTimeEntry,
	MissingTimeStatCard,
	PayCodeConfig,
	PayCodeStats,
	TimeApprovalEntry,
	TimekeepingStatCard,
} from "@repo/ui/general/timekeeping/types";
import {
	AlertTriangle,
	Building2,
	Calendar,
	Check,
	CheckCircle,
	Clock,
	DollarSign,
	FileUp,
	Landmark,
	Layers,
	Smartphone,
	Users,
	XCircle,
} from "lucide-react";

export const TIMEKEEPING_POLICY_DEFAULTS = {
	submissionDeadlineDays: 3,
	reminderIntervalDays: 2,
	autoApproveAfterDays: 3,
} as const;

export const PAY_CODE_BADGE_VARIANT: Record<
	string,
	"outline" | "warning" | "info" | "success"
> = {
	REG: "outline",
	Regular: "outline",
	Training: "outline",
	OT: "warning",
	"Double Time": "warning",
	PTO: "success",
	Holiday: "info",
	Sick: "info",
	Bereavement: "info",
	"Jury Duty": "info",
	"On-Call": "warning",
};

export const WORKER_TYPE_BADGE_VARIANT: Record<string, BadgeVariants> = {
	Contract: "info",
	"Per Diem": "success",
	Travel: "violet",
	Staff: "secondary",
};

export const PAY_CODE_CONFIG: PayCodeConfig[] = [
	{
		category: "Standard Time",
		codes: [
			{
				code: "Regular",
				description: "Regular hours worked during standard shift",
				multiplier: "1.0x",
			},
			{
				code: "Training",
				description: "Paid training time",
				multiplier: "1.0x",
			},
		],
	},
	{
		category: "Overtime",
		codes: [
			{
				code: "OT",
				description: "Overtime hours (over 40 hours per week)",
				multiplier: "1.5x",
			},
			{
				code: "Double Time",
				description:
					"Double time hours (over 12 hours in a day or 7th consecutive day)",
				multiplier: "2.0x",
			},
		],
	},
	{
		category: "Paid Leave",
		codes: [
			{ code: "PTO", description: "Paid time off", multiplier: "1.0x" },
			{ code: "Holiday", description: "Holiday pay", multiplier: "1.0x" },
			{ code: "Sick", description: "Sick leave", multiplier: "1.0x" },
			{
				code: "Bereavement",
				description: "Bereavement leave",
				multiplier: "1.0x",
			},
			{ code: "Jury Duty", description: "Jury duty leave", multiplier: "1.0x" },
		],
	},
	{
		category: "Special Pay",
		codes: [
			{
				code: "On-Call",
				description: "On-call availability pay",
				multiplier: "Varies",
			},
		],
	},
];

export const TIMEKEEPING_STATUS_OPTIONS = [
	{ value: "ALL", label: "All Statuses" },
	{ value: "Open", label: "Open" },
	{ value: "Resolved", label: "Resolved" },
	{ value: "Rejected", label: "Rejected" },
];

export const DATA_SOURCE_OPTIONS: { value: string; label: string }[] = [
	{ value: "ALL", label: "All Sources" },
	{ value: "FILE_UPLOAD", label: "File / Integration" },
	{ value: "MOBILE_APP", label: "Mobile App" },
];

export const TIMEKEEPING_STATUS_FILTER_OPTIONS: {
	key: ApprovalStatusFilter;
	label: string;
}[] = [
	{ key: "ALL", label: "All" },
	{ key: "PENDING", label: "Pending" },
	{ key: "APPROVED", label: "Approved" },
	{ key: "DISPUTED", label: "Disputed" },
];

export const MOCK_TIMEKEEPING_LOCATIONS: LocationTimekeeping[] = [
	{
		id: "loc-1",
		name: "Memorial Hospital",
		entryCount: 2,
		totalHours: 88,
		departments: [
			{
				id: "dept-1",
				name: "ICU",
				workerCount: 1,
				totalHours: 36,
				workers: [
					{
						id: "worker-1",
						name: "Sarah Johnson",
						position: "Registered Nurse - ICU",
						source: "MOBILE_APP",
						status: "PENDING",
						regularHours: 32,
						overtimeHours: 8,
						totalHours: 40,
						timeLogs: [
							{
								id: "log-1",
								startDate: "2025-01-15",
								endDate: "2025-01-15",
								payCode: "Regular",
								startTime: "07:00 AM",
								endTime: "03:00 PM",
								totalHours: 8,
								note: null,
								status: "APPROVED",
								approvalSource: "Auto",
								source: "MOBILE_APP",
							},
							{
								id: "log-2",
								startDate: "2025-01-16",
								endDate: "2025-01-16",
								payCode: "Regular",
								startTime: "07:00 AM",
								endTime: "03:00 PM",
								totalHours: 8,
								note: null,
								status: "APPROVED",
								approvalSource: "Manual",
								source: "MOBILE_APP",
							},
							{
								id: "log-3",
								startDate: "2025-01-17",
								endDate: "2025-01-17",
								payCode: "Regular",
								startTime: "07:00 AM",
								endTime: "03:00 PM",
								totalHours: 8,
								note: null,
								status: "PENDING",
								source: "MOBILE_APP",
							},
							{
								id: "log-4",
								startDate: "2025-01-18",
								endDate: "2025-01-18",
								payCode: "Regular",
								startTime: "07:00 AM",
								endTime: "03:00 PM",
								totalHours: 8,
								note: null,
								status: "PENDING",
								source: "MOBILE_APP",
							},
							{
								id: "log-5",
								startDate: "2025-01-18",
								endDate: "2025-01-18",
								payCode: "OT",
								startTime: "03:00 PM",
								endTime: "07:00 PM",
								totalHours: 4,
								note: "Extra shift coverage",
								status: "PENDING",
								source: "MOBILE_APP",
							},
							{
								id: "log-11",
								startDate: "2025-01-19",
								endDate: "2025-01-19",
								payCode: "Double Time",
								startTime: "07:00 AM",
								endTime: "11:00 AM",
								totalHours: 4,
								note: "Emergency weekend shift",
								status: "PENDING",
								source: "MOBILE_APP",
							},
						],
					},
				],
			},
			{
				id: "dept-2",
				name: "Emergency",
				workerCount: 1,
				totalHours: 52,
				workers: [
					{
						id: "worker-2",
						name: "Michael Chen",
						position: "Registered Nurse - Emergency",
						source: "FILE_UPLOAD",
						status: "APPROVED",
						regularHours: 48,
						overtimeHours: 4,
						totalHours: 52,
						timeLogs: [
							{
								id: "log-6",
								startDate: "2025-01-15",
								endDate: "2025-01-15",
								payCode: "Regular",
								startTime: "07:00 PM",
								endTime: "07:00 AM",
								totalHours: 12,
								note: null,
								status: "APPROVED",
								approvalSource: "Auto",
								source: "FILE_UPLOAD",
							},
							{
								id: "log-7",
								startDate: "2025-01-17",
								endDate: "2025-01-17",
								payCode: "Regular",
								startTime: "07:00 PM",
								endTime: "07:00 AM",
								totalHours: 12,
								note: null,
								status: "APPROVED",
								approvalSource: "Manual",
								source: "FILE_UPLOAD",
							},
						],
					},
				],
			},
		],
	},
	{
		id: "loc-2",
		name: "Spring Valley Rehab",
		entryCount: 1,
		totalHours: 41,
		departments: [
			{
				id: "dept-3",
				name: "Rehabilitation",
				workerCount: 1,
				totalHours: 41,
				workers: [
					{
						id: "worker-3",
						name: "Jessica Park",
						position: "Physical Therapist",
						source: "MOBILE_APP",
						status: "PENDING",
						regularHours: 40,
						overtimeHours: 1,
						totalHours: 41,
						timeLogs: [
							{
								id: "log-8",
								startDate: "2025-01-15",
								endDate: "2025-01-15",
								payCode: "Regular",
								startTime: "08:00 AM",
								endTime: "04:00 PM",
								totalHours: 8,
								note: null,
								status: "PENDING",
								source: "MOBILE_APP",
							},
						],
					},
				],
			},
		],
	},
	{
		id: "loc-3",
		name: "Lakewood Medical",
		entryCount: 2,
		totalHours: 80,
		departments: [
			{
				id: "dept-4",
				name: "Medical-Surgical",
				workerCount: 1,
				totalHours: 38,
				workers: [
					{
						id: "worker-4",
						name: "David Kim",
						position: "Licensed Practical Nurse",
						source: "FILE_UPLOAD",
						status: "DISPUTED",
						regularHours: 36,
						overtimeHours: 2,
						totalHours: 38,
						timeLogs: [
							{
								id: "log-9",
								startDate: "2025-01-16",
								endDate: "2025-01-16",
								payCode: "Regular",
								startTime: "03:00 PM",
								endTime: "11:00 PM",
								totalHours: 8,
								note: null,
								status: "DISPUTED",
								source: "FILE_UPLOAD",
							},
						],
					},
				],
			},
			{
				id: "dept-5",
				name: "Cardiology",
				workerCount: 1,
				totalHours: 42,
				workers: [
					{
						id: "worker-5",
						name: "Emily Torres",
						position: "Registered Nurse - Cardiology",
						source: "MOBILE_APP",
						status: "PENDING",
						regularHours: 40,
						overtimeHours: 2,
						totalHours: 42,
						timeLogs: [
							{
								id: "log-10",
								startDate: "2025-01-18",
								endDate: "2025-01-18",
								payCode: "Regular",
								startTime: "07:00 AM",
								endTime: "03:00 PM",
								totalHours: 8,
								note: null,
								status: "PENDING",
								source: "MOBILE_APP",
							},
						],
					},
				],
			},
		],
	},
];

export const MOCK_STAT_CARDS: TimekeepingStatCard[] = [
	{
		key: "total",
		label: "Total Entries",
		value: 13,
		subLabel: "All sources",
		icon: Layers,
		variant: "default",
	},
	{
		key: "file",
		label: "File Upload",
		value: 6,
		subLabel: "File/Integration source",
		icon: FileUp,
		variant: "primary",
	},
	{
		key: "mobile",
		label: "Mobile App",
		value: 7,
		subLabel: "Manual entry source",
		icon: Smartphone,
		variant: "primary",
	},
	{
		key: "hours",
		label: "Total Hours",
		value: 553,
		subLabel: "Current timekeeping cycle (weekly)",
		icon: Clock,
		variant: "default",
	},
	{
		key: "disputes",
		label: "Open Disputes",
		value: 3,
		subLabel: "Needs review",
		icon: AlertTriangle,
		variant: "error",
	},
];

export const MOCK_PAYCODE_STATS: PayCodeStats[] = [
	{
		key: "total-pay-codes",
		label: "Total Pay Codes",
		value: 10,
		icon: DollarSign,
		variant: "primary",
	},
	{
		key: "categories",
		label: "Categories",
		value: 4,
		icon: Layers,
		variant: "primary",
	},
	{
		key: "overtime-types",
		label: "Overtime Types",
		value: 2,
		icon: Clock,
		variant: "primary",
	},
];

export const MOCK_APPROVAL_STAT_CARDS: TimekeepingStatCard[] = [
	{
		key: "pending",
		label: "Total Pending",
		value: 5,
		subLabel: "Awaiting approval",
		icon: Clock,
		variant: "warning",
	},
	{
		key: "approved",
		label: "Approved This Period",
		value: 3,
		subLabel: "Last 30 days",
		icon: Check,
		variant: "success",
	},
	{
		key: "disputed",
		label: "Disputed",
		value: 2,
		subLabel: "Requiring resolution",
		icon: AlertTriangle,
		variant: "error",
	},
];

export const MOCK_APPROVAL_ENTRIES: TimeApprovalEntry[] = [
	{
		id: "1",
		workerName: "Sarah Johnson",
		position: "Registered Nurse - ICU",
		startDate: "2025-01-13",
		endDate: "2025-01-19",
		regularHours: 40,
		overtimeHours: 8,
		totalHours: 48,
		status: "PENDING",
		pendingDays: 0,
		startTime: "07:00 AM",
		endTime: "03:00 PM",
		payCode: "Regular",
		source: "MOBILE_APP",
		note: null,
	},
	{
		id: "2",
		workerName: "Michael Chen",
		position: "Physical Therapist",
		startDate: "2025-01-13",
		endDate: "2025-01-19",
		regularHours: 32,
		overtimeHours: 0,
		totalHours: 32,
		status: "PENDING",
		pendingDays: 1,
		startTime: "08:00 AM",
		endTime: "04:00 PM",
		payCode: "Regular",
		source: "MOBILE_APP",
		note: null,
	},
	{
		id: "3",
		workerName: "David Thompson",
		position: "Registered Nurse - Emergency",
		startDate: "2025-01-13",
		endDate: "2025-01-19",
		regularHours: 40,
		overtimeHours: 4,
		totalHours: 44,
		status: "PENDING",
		pendingDays: 3,
		isAutoApproved: true,
		startTime: "07:00 PM",
		endTime: "07:00 AM",
		payCode: "Regular",
		source: "FILE_UPLOAD",
		note: null,
	},
	{
		id: "4",
		workerName: "Amanda Brooks",
		position: "Registered Nurse - Medical Surgical",
		startDate: "2025-01-06",
		endDate: "2025-01-12",
		regularHours: 40,
		overtimeHours: 12,
		totalHours: 52,
		status: "APPROVED",
		startTime: "03:00 PM",
		endTime: "11:00 PM",
		payCode: "Regular",
		source: "MOBILE_APP",
		note: "Busy week in surgical unit",
	},
	{
		id: "5",
		workerName: "Christopher Lee",
		position: "Occupational Therapist",
		startDate: "2025-01-06",
		endDate: "2025-01-12",
		regularHours: 40,
		overtimeHours: 0,
		totalHours: 40,
		status: "APPROVED",
		startTime: "09:00 AM",
		endTime: "05:00 PM",
		payCode: "Regular",
		source: "MOBILE_APP",
		note: null,
	},
	{
		id: "6",
		workerName: "Jennifer White",
		position: "Certified Nursing Assistant",
		startDate: "2025-01-06",
		endDate: "2025-01-12",
		regularHours: 32,
		overtimeHours: 8,
		totalHours: 40,
		status: "APPROVED",
		startTime: "07:00 AM",
		endTime: "03:00 PM",
		payCode: "Regular",
		source: "FILE_UPLOAD",
		note: null,
	},
	{
		id: "7",
		workerName: "Robert Martinez",
		position: "Registered Nurse - ICU",
		startDate: "2025-01-13",
		endDate: "2025-01-19",
		regularHours: 40,
		overtimeHours: 4,
		totalHours: 44,
		status: "DISPUTED",
		startTime: "07:00 AM",
		endTime: "03:00 PM",
		payCode: "Regular",
		source: "MOBILE_APP",
		note: "Punch clock error",
	},
	{
		id: "8",
		workerName: "Lisa Thompson",
		position: "Speech Therapist",
		startDate: "2025-01-06",
		endDate: "2025-01-12",
		regularHours: 35,
		overtimeHours: 0,
		totalHours: 35,
		status: "DISPUTED",
		startTime: "08:00 AM",
		endTime: "03:00 PM",
		payCode: "Regular",
		source: "MOBILE_APP",
		note: null,
	},
];

export const MOCK_DISPUTE_STAT_CARDS: DisputeStatCard[] = [
	{
		key: "open",
		label: "Open Disputes",
		value: 2,
		subLabel: "Requires action",
		icon: AlertTriangle,
		variant: "error",
	},
	{
		key: "resolved",
		label: "Resolved",
		value: 2,
		subLabel: "Accepted & corrected",
		icon: CheckCircle,
		variant: "success",
	},
	{
		key: "rejected",
		label: "Rejected",
		value: 1,
		subLabel: "No changes made",
		icon: XCircle,
		variant: "inactive",
	},
];

export const MOCK_DISPUTE_LOGS: DisputeLogEntry[] = [
	{
		id: "disp-1",
		workerName: "David Thompson",
		position: "Registered Nurse - Emergency",
		date: "2025-01-19",
		startTime: "07:00 PM",
		endTime: "09:00 PM",
		payCode: "OT",
		hours: 2,
		source: "FILE_UPLOAD",
		disputeReason: "Hours mismatch with approved schedule",
		submittedBy: {
			name: "MedStaff Solutions",
			role: "Vendor",
			timestamp: "2025-01-23T10:30:00Z",
		},
		status: "Open",
	},
	{
		id: "disp-2",
		workerName: "Sarah Johnson",
		position: "Registered Nurse - ICU",
		date: "2025-01-12",
		startTime: "07:00 AM",
		endTime: "03:00 PM",
		payCode: "Regular",
		hours: 8,
		source: "MOBILE_APP",
		disputeReason:
			"Worker clocked out early due to emergency, should be 6 hours",
		resolution: "Confirmed with supervisor - adjusted to 6 hours",
		submittedBy: {
			name: "Internal Review",
			role: "System",
			timestamp: "2025-01-15T14:15:00Z",
		},
		resolvedAt: "2025-01-16T09:00:00Z",
		status: "Resolved",
	},
	{
		id: "disp-3",
		workerName: "Michael Chen",
		position: "Registered Nurse - Emergency",
		date: "2025-01-10",
		startTime: "07:00 PM",
		endTime: "10:00 PM",
		payCode: "OT",
		hours: 3,
		source: "FILE_UPLOAD",
		disputeReason: "Overtime not pre-approved per contract terms",
		resolution:
			"Overtime was approved by on-duty manager due to staffing emergency",
		submittedBy: {
			name: "HealthForce Partners",
			role: "Vendor",
			timestamp: "2025-01-13T11:45:00Z",
		},
		resolvedAt: "2025-01-14T15:30:00Z",
		status: "Rejected",
	},
	{
		id: "disp-4",
		workerName: "James Wilson",
		position: "Respiratory Therapist",
		date: "2025-01-18",
		startTime: "04:00 PM",
		endTime: "08:00 PM",
		payCode: "Double Time",
		hours: 4,
		source: "MOBILE_APP",
		disputeReason: "Should be classified as regular overtime, not double time",
		submittedBy: {
			name: "Finance Department",
			role: "Internal",
			timestamp: "2025-01-22T13:00:00Z",
		},
		status: "Open",
	},
	{
		id: "disp-5",
		workerName: "Lisa Anderson",
		position: "Certified Nursing Assistant",
		date: "2025-01-14",
		startTime: "07:00 AM",
		endTime: "03:00 PM",
		payCode: "PTO",
		hours: 8,
		source: "FILE_UPLOAD",
		disputeReason: "PTO request was not in system, worker was actually present",
		resolution: "Confirmed worker was on site - changed to Regular hours",
		submittedBy: {
			name: "HR Department",
			role: "Internal",
			timestamp: "2025-01-17T09:20:00Z",
		},
		resolvedAt: "2025-01-18T10:15:00Z",
		status: "Resolved",
	},
];

export const MOCK_MISSING_TIME_STAT_CARDS: MissingTimeStatCard[] = [
	{
		key: "workers",
		label: "Workers Missing Time",
		value: 5,
		subLabel: "Needs follow-up",
		icon: Users,
		variant: "error",
	},
	{
		key: "days",
		label: "Total Missing Days",
		value: 13,
		subLabel: "Unsubmitted entries",
		icon: Calendar,
		variant: "warning",
	},
	{
		key: "overdue",
		label: "Overdue (>2 days)",
		value: 2,
		subLabel: "Immediate action required",
		icon: AlertTriangle,
		variant: "error",
	},
];

export const MOCK_MISSING_TIME_ENTRIES: MissingTimeEntry[] = [
	{
		id: "mte-1",
		status: "Overdue",
		workerName: "Thomas Anderson",
		workerType: "Contract",
		location: "Memorial Hospital",
		department: "ICU",
		position: "Registered Nurse - ICU",
		missingDates: ["2025-01-22", "2025-01-23", "2025-01-24"],
		lastSubmitted: "2025-01-21",
		daysOverdue: 3,
	},
	{
		id: "mte-2",
		status: "Pending",
		workerName: "Rebecca Martinez",
		workerType: "Per Diem",
		location: "Spring Valley Rehab",
		department: "Rehabilitation",
		position: "Occupational Therapist",
		missingDates: ["2025-01-23", "2025-01-24"],
		lastSubmitted: "2025-01-20",
		daysOverdue: 2,
	},
	{
		id: "mte-3",
		status: "Pending",
		workerName: "Kevin Park",
		workerType: "Contract",
		location: "Lakewood Medical",
		department: "Medical-Surgical",
		position: "Licensed Practical Nurse",
		missingDates: ["2025-01-24"],
		lastSubmitted: "2025-01-21",
		daysOverdue: 1,
	},
	{
		id: "mte-4",
		status: "Overdue",
		workerName: "Angela Washington",
		workerType: "Travel",
		location: "Memorial Hospital",
		department: "Emergency",
		position: "Emergency Room Nurse",
		missingDates: [
			"2025-01-20",
			"2025-01-21",
			"2025-01-22",
			"2025-01-23",
			"2025-01-24",
		],
		lastSubmitted: "2025-01-14",
		daysOverdue: 5,
	},
];

export const MOCK_HOLIDAYS: HolidayEntry[] = [
	{
		id: "hol-1",
		name: "New Year's Day",
		date: "2025-01-01",
		type: "Federal",
	},
	{
		id: "hol-2",
		name: "Martin Luther King Jr. Day",
		date: "2025-01-20",
		type: "Federal",
	},
	{
		id: "hol-3",
		name: "Presidents' Day",
		date: "2025-02-17",
		type: "Federal",
	},
	{
		id: "hol-4",
		name: "Memorial Day",
		date: "2025-05-26",
		type: "Federal",
	},
	{
		id: "hol-5",
		name: "Juneteenth",
		date: "2025-06-19",
		type: "Federal",
	},
	{
		id: "hol-6",
		name: "Independence Day",
		date: "2025-07-04",
		type: "Federal",
	},
	{
		id: "hol-7",
		name: "Labor Day",
		date: "2025-09-01",
		type: "Federal",
	},
	{
		id: "hol-8",
		name: "Columbus Day",
		date: "2025-10-13",
		type: "Federal",
	},
	{
		id: "hol-9",
		name: "Veterans Day",
		date: "2025-11-11",
		type: "Federal",
	},
	{
		id: "hol-10",
		name: "Thanksgiving Day",
		date: "2025-11-27",
		type: "Federal",
	},
	{
		id: "hol-11",
		name: "Christmas Day",
		date: "2025-12-25",
		type: "Federal",
	},
];

export const MOCK_HOLIDAY_STATS: HolidayStats[] = [
	{
		key: "total-holidays",
		label: "Total Holidays",
		value: 11,
		icon: Calendar,
		variant: "primary",
	},
	{
		key: "federal-holidays",
		label: "Federal Holidays",
		value: 11,
		icon: Landmark,
		variant: "primary",
	},
	{
		key: "remaining-holidays",
		label: "Remaining Holidays",
		value: 6,
		icon: Building2,
		variant: "primary",
	},
];
