-- AlterEnum
ALTER TYPE "ComplianceListItemCategory" ADD VALUE IF NOT EXISTS 'EMPLOYEE_HEALTH';
ALTER TYPE "ComplianceListItemCategory" ADD VALUE IF NOT EXISTS 'IMMIGRATION';
ALTER TYPE "ComplianceListItemCategory" ADD VALUE IF NOT EXISTS 'ASSESSMENTS';
ALTER TYPE "ComplianceListItemCategory" ADD VALUE IF NOT EXISTS 'CLIENT_POLICY';
