encryptionsalt: v1:hAYGzKOQoSk=:v1:f1gB7qRMWYbBEpk/:BVVrsW02ndWS/V8ZSPqzRb00+xMJkQ==
config:
  aws:region: us-east-1
  workforce-infra:authSecret:
    secure: v1:KdYEsbsoUIzh2mXl:w82qKrtbKqAzDg9w/dzilDEjKkJ9ZbkgK9bMD7Ev8qZWzTEdGVcgXP7a1LdtPPB1ccGGJXYLs8+OzmW6auoNyIQZbBvuQ7Q+6/tgtHOa19c=
  workforce-infra:dbPassword:
    secure: v1:vExnxWh+AY07QyUs:YaetZd3DTiQMmOT7Rn5Bji4AOBfR7hJpDhlxXZ+eF0LdBqsqu6Q6VA5s7P6Puh9TipGN+0nWFhaYOChhCG5C/g==
  workforce-infra:smtpUser:
    secure: v1:qc/NQEswYjte9fCY:u1hFqru9NvlHw2WuG2FVYHRnZLpnRfSAHL6Od77GdlMNpcTl
  workforce-infra:smtpPassword:
    secure: v1:EDfGkLyyLEywFEoa:czrbh4uhTn4kWQhzXEhRfpD0DnU8jOqN49eNAuWXeoLqpjEUsNOK4kXoBPfV/F7aD/6okGTcp/ZTqz9Z
