import type { InvoiceApproval } from "@/types/billing-approval";

export const MOCK_INVOICE_APPROVALS: InvoiceApproval[] = [
	{
		id: "1",
		invoiceNumber: "INV-2025-004",
		status: "pending",
		cycleType: "WEEKLY",
		startDate: "2025-01-01",
		endDate: "2025-01-07",
		submittedDate: "2025-01-08",
		totalAmount: 67890.0,
		departments: 3,
		totalHours: 312,
		disputeWindowDays: 3,
		departmentDetails: [
			{
				id: "d1",
				name: "Family Medicine",
				costCenter: "Family Medicine - North",
				candidatesCount: 4,
				hours: 156,
				amount: 14820.0,
				entries: [
					{
						id: "c1",
						name: "Sarah Thompson",
						role: "Registered Nurse",
						source: "mobile",
						regularHrs: 40,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 95,
						total: 3800,
						status: "Validated",
					},
					{
						id: "c2",
						name: "Michael Anderson",
						role: "Physical Therapist",
						source: "upload",
						regularHrs: 32,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 88,
						total: 2816,
						status: "Validated",
					},
					{
						id: "c3",
						name: "Jennifer Martinez",
						role: "Registered Nurse",
						source: "mobile",
						regularHrs: 40,
						otHrs: 4,
						holidayHrs: 0,
						billRate: 98,
						total: 4508,
						status: "Validated",
					},
					{
						id: "c4",
						name: "Robert Williams",
						role: "Respiratory Therapist",
						source: "mobile",
						regularHrs: 40,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 92,
						total: 3680,
						status: "Validated",
					},
				],
			},
			{
				id: "d2",
				name: "Emergency Department",
				costCenter: "Emergency - Main",
				candidatesCount: 3,
				hours: 124,
				amount: 11568.0,
				entries: [
					{
						id: "c5",
						name: "Amanda Chen",
						role: "Registered Nurse",
						source: "mobile",
						regularHrs: 40,
						otHrs: 8,
						holidayHrs: 0,
						billRate: 96,
						total: 4992,
						status: "Validated",
					},
					{
						id: "c6",
						name: "David Johnson",
						role: "Respiratory Therapist",
						source: "upload",
						regularHrs: 36,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 91,
						total: 3276,
						status: "Validated",
					},
					{
						id: "c7",
						name: "Lisa Brown",
						role: "Registered Nurse",
						source: "mobile",
						regularHrs: 40,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 93,
						total: 3720,
						status: "Validated",
					},
				],
			},
			{
				id: "d3",
				name: "Intensive Care Unit",
				costCenter: "ICU - Level 3",
				candidatesCount: 2,
				hours: 80,
				amount: 7840.0,
				entries: [
					{
						id: "c8",
						name: "Christopher Davis",
						role: "Registered Nurse",
						source: "mobile",
						regularHrs: 40,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 99,
						total: 3960,
						status: "Validated",
					},
					{
						id: "c9",
						name: "Emily White",
						role: "Registered Nurse",
						source: "upload",
						regularHrs: 40,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 97,
						total: 3880,
						status: "Validated",
					},
				],
			},
		],
	},
	{
		id: "2",
		invoiceNumber: "INV-2025-005",
		status: "pending",
		cycleType: "WEEKLY",
		startDate: "2025-01-08",
		endDate: "2025-01-14",
		submittedDate: "2025-01-15",
		totalAmount: 127540.0,
		departments: 4,
		totalHours: 468,
		disputeWindowDays: 3,
		departmentDetails: [
			{
				id: "d4",
				name: "Surgical Services",
				costCenter: "Surgery - Main",
				candidatesCount: 3,
				hours: 120,
				amount: 15600.0,
				entries: [
					{
						id: "c10",
						name: "James Wilson",
						role: "Surgical Nurse",
						source: "mobile",
						regularHrs: 40,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 130,
						total: 5200,
						status: "Validated",
					},
				],
			},
		],
	},
	{
		id: "3",
		invoiceNumber: "INV-2025-003",
		status: "disputed",
		cycleType: "WEEKLY",
		startDate: "2024-12-25",
		endDate: "2024-12-31",
		submittedDate: "2025-01-01",
		totalAmount: 89420.0,
		departments: 2,
		totalHours: 356,
		disputeWindowDays: 1,
		departmentDetails: [
			{
				id: "d5",
				name: "Pediatrics",
				costCenter: "Peds - West",
				candidatesCount: 2,
				hours: 80,
				amount: 7200.0,
				entries: [
					{
						id: "c11",
						name: "Linda Garcia",
						role: "Pediatric Nurse",
						source: "upload",
						regularHrs: 40,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 90,
						total: 3600,
						status: "Validated",
					},
				],
			},
		],
	},
	{
		id: "4",
		invoiceNumber: "INV-2025-006",
		status: "pending",
		cycleType: "WEEKLY",
		startDate: "2025-01-15",
		endDate: "2025-01-21",
		submittedDate: "2025-01-22",
		totalAmount: 98750.0,
		departments: 3,
		totalHours: 392,
		disputeWindowDays: 3,
		departmentDetails: [
			{
				id: "d6",
				name: "Radiology",
				costCenter: "Rad - Center",
				candidatesCount: 2,
				hours: 72,
				amount: 8280.0,
				entries: [
					{
						id: "c12",
						name: "Robert Moore",
						role: "Radiologic Tech",
						source: "mobile",
						regularHrs: 36,
						otHrs: 0,
						holidayHrs: 0,
						billRate: 115,
						total: 4140,
						status: "Validated",
					},
				],
			},
		],
	},
];
