export enum ComplianceListItemCategory {
	BACKGROUND_AND_IDENTIFICATION = "BACKGROUND_AND_IDENTIFICATION",
	CERTIFICATIONS = "CERTIFICATIONS",
	EMPLOYEE_HEALTH = "EMPLOYEE_HEALTH",
	IMMIGRATION = "IMMIGRATION",
	LICENSES = "LICENSES",
	ASSESSMENTS = "ASSESSMENTS",
	CLIENT_POLICY = "CLIENT_POLICY",
	OTHERS = "OTHERS",
}

export enum ComplianceListItemExpirationType {
	EXPIRATION_DATE = "EXPIRATION_DATE",
	EXPIRATION_RULE = "EXPIRATION_RULE",
	NON_EXPIRABLE = "NON_EXPIRABLE",
}

export enum ComplianceListItemResponseStyle {
	PENDING_FILE_UPLOAD = "PENDING_FILE_UPLOAD",
	INTERNAL_TASK = "INTERNAL_TASK",
	DOWNLOAD_AND_UPLOAD = "DOWNLOAD_AND_UPLOAD",
	LINK = "LINK",
}

export enum ComplianceListItemStatus {
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
}

export enum ExpirationRuleUnit {
	DAYS = "DAYS",
	MONTHS = "MONTHS",
	YEARS = "YEARS",
}

export enum ComplianceChecklistItemPhase {
	SUBMISSION = "SUBMISSION",
	PLACEMENT = "PLACEMENT",
}
