export enum MatchingCriterionKey {
	PREFERRED_LOCATION = "PREFERRED_LOCATION",
	SHIFT_TYPE = "SHIFT_TYPE",
	CONTRACT_LENGTH = "CONTRACT_LENGTH",
	OCCUPATION = "OCCUPATION",
	SPECIALTIES = "SPECIALTIES",
}
