/** Mirrors Prisma `MetricType`. Keep synchronized with schema.prisma. */
export enum MetricType {
	RECRUITMENT_EFFICIENCY = "RECRUITMENT_EFFICIENCY",
	COMPLIANCE = "COMPLIANCE",
	QUALITY_OF_SERVICE = "QUALITY_OF_SERVICE",
}

/** Mirrors Prisma `MetricKey`. Keep synchronized with schema.prisma. */
export enum MetricKey {
	REJECTION_PERCENTAGE = "REJECTION_PERCENTAGE",
	FILL_RATE_LONG_TERM_REQS = "FILL_RATE_LONG_TERM_REQS",
	FILL_RATE_SHIFTS = "FILL_RATE_SHIFTS",
	SUBMIT_TO_OFFER_RATIO = "SUBMIT_TO_OFFER_RATIO",
	AVG_TIME_TO_FIRST_SUBMISSION = "AVG_TIME_TO_FIRST_SUBMISSION",
	AVG_TIME_PUBLISH_TO_ACCEPT = "AVG_TIME_PUBLISH_TO_ACCEPT",
	PERCENT_INCOMPLETE_ASSIGNMENTS = "PERCENT_INCOMPLETE_ASSIGNMENTS",
	EXPIRED_CREDENTIALING_PERCENT = "EXPIRED_CREDENTIALING_PERCENT",
	ON_TIME_STARTS_PERCENT = "ON_TIME_STARTS_PERCENT",
	BACK_OUT_PERCENTAGE = "BACK_OUT_PERCENTAGE",
	PERFORMANCE_GRIEVANCE_PERCENT = "PERFORMANCE_GRIEVANCE_PERCENT",
	GRIEVANCE_PERCENTAGE = "GRIEVANCE_PERCENTAGE",
}
